[package]
name = "doodle_gencode"
version = "0.1.0"
edition = "2021"

[lib]
bench = false
path = "gencode.rs"

[[bin]]
path = "bin/pnginfo.rs"
name = "pnginfo"

[[bin]]
path = "bin/fontinfo.rs"
name = "fontinfo"

[[bench]]
name = "gen_benchmark"
path = "benches/gen_benchmark.rs"
harness = false

[dev-dependencies]
criterion = "0.5"

[dependencies]
doodle = { path = "../", version = "0.1.0" }
encoding = "0.2"
clap = { version = "4.2", features = ["derive"] }
derive_builder = "0.20.2"
